language: cpp
compiler: clang
before_script:
- sudo apt update
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list.d/xenial.list
- sudo apt-get install doxygen -y
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen
deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: doxygen/html
    on:
      branch: master
  - provider: script
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uolpotkin:$BINTRAY_API_KEY "https://api.bintray.com/content/olpotkin/OTUS-CPP-COURSE/otus-hometask/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
